sudo: required
services:
  - docker

before_install:
  - docker build -t perdita997/devops-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true perdita997/devops-docker-react npm run test -- --coverage --watchAll=false